problem:
  name: Project01
  template_case: 'case'
  type: 'param_variation'
  models: auto
  parameters:
    Sv:
      type: range
      value_type: float
      bounds: [1e-5, 1e-3]
      log_scale: False
    xmin:
      type: choice
      value_type: float
      values: [0.01, 0.02, 0.03, 0.04]
      is_ordered: True
    xmax:
      type: choice
      value_type: float
      values: [0.05, 0.06, 0.07, 0.09]
      is_ordered: True
    ymin:
      type: choice
      value_type: float
      values: [0.01, 0.02, 0.03, 0.04]
      is_ordered: True
    ymax:
      type: choice
      value_type: float
      values: [0.05, 0.06, 0.07, 0.09]
      is_ordered: True
    numberOfSubdomains:
      type: range
      value_type: int
      bounds: [4, 8]
      log_scale: False
  scopes:
    "/system/fvOptions":
      Sv: "codedSource.Sv"
      xmin: "codedSource.xmin"
      xmax: "codedSource.xmax"
      ymin: "codedSource.ymin"
      ymax: "codedSource.ymax"
    "/system/decomposeParDict":
      numberOfSubdomains: "numberOfSubdomains"
  objectives:
    MaxError:
      mode: 'shell'
      command: ['awk', '/^Max/{print($6+0)}', 'log.pvpython']
      threshold: 1e-6
      minimize: True
      lower_is_better: True

meta:
  case_subdirs_to_clone:
    - 0.orig
    - dynamicCode
    - error.py
    - plotK.py
  clone_destination: "./"
  case_run_mode: local
  metric_value_mode: local
  case_run_command: ['./Allrun']
  n_trials: 15
  n_parallel_trials: 4
  ttl_trial: 3600
  init_poll_wait: 0.1
  poll_factor: 1.5
  timeout: 10
  use_saasbo: False
  n_pareto_points: 5
  stopping_strategy:
    improvement_bar: 1e-4
    min_trials: 300
    window_size: 10

visualize:
  update_interval: 15
  n_latest_trials: 3
  zscore_bar: 15
  graph_height: 400
  host: '0.0.0.0'
  port: 8888
